[package]
name = "formulas-ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "formulas_ffi"
crate-type = ["cdylib", "staticlib"]

[dependencies]
formulas = { path = "../formulas" }
